SELECT
    SEQ
    ,BOARD_ID
    ,CATEGORY_ID
    ,SUBJECT
    ,CONTENTS
    ,READ_CNT
    ,RECOMMEND_CNT
    ,COMMENTS_CNT
    ,IMAGE_EXIST_YN
    ,NICKNAME
    ,SECRET
    ,DELETED_YN
    ,DELETED_DT
    ,CREATE_USER
    ,CREATE_DT
    ,UPDATE_USER
    ,UPDATE_DT
FROM TB_BOARD
WHERE SEQ = @SEQ
AND DELETED_YN = 'N'