SELECT ID
	  ,YOUTUBE_ID
	  ,CHANNEL_NAME
	  ,TITLE
	  ,THUMBNAIL_IMG_URL
	  ,VIEW_CNT
	  ,LIKE_CNT
	  ,DISLIKE_CNT
	  ,COMMENT_CNT
	  ,PUBLISH_DT
	  ,URL
	  ,DELETED_YN
	  ,DELETED_DT
	  ,CREATE_DT
	  ,UPDATE_DT
  FROM TB_YOUTUBE_DATA