SELECT
    SEQ
    ,BOARD_ID
    ,CATEGORY_ID
    ,SUBJECT
    ,CONTENTS
    ,READ_CNT
    ,RECOMMEND_CNT
    ,COMMENTS_CNT
    ,IMAGE_EXIST_YN
    ,NICKNAME
    ,SECRET
    ,DELETED_YN
    ,DELETED_DT
    ,CREATE_USER
    ,CREATE_DT
    ,UPDATE_USER
    ,UPDATE_DT
FROM TB_BOARD
WHERE CATEGORY_ID LIKE CONCAT('%', @CATEGORY_ID, '%')
  AND 
  CASE WHEN @SUBJECT = @CONTENTS THEN
	(SUBJECT LIKE CONCAT('%', @SUBJECT,'%') OR CONTENTS LIKE CONCAT('%', @CONTENTS, '%'))
  ELSE (SUBJECT LIKE CONCAT('%', @SUBJECT,'%') AND CONTENTS LIKE CONCAT('%', @CONTENTS, '%'))
  END
  AND DELETED_YN = 'N'
